version: '3'

######### Services ###################################

services:
  # Server container
  nginx:
    build:
      context: docker/dev/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/dev/nginx/logs:/var/log/nginx
    ports:
      # vue port
      - 8080:80
      # Laravel port
      - 8081:81
    depends_on:
      - client
      - php

  # PHP FastCGI Process Manager container
  php:
    build:
      context: docker/dev/php
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/api
    environment:
      # If you down want to use xDebug, set remote_enable=0
      XDEBUG_CONFIG: "remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - postgres
      - postgres-testing

  # PostgreSQL database container
  postgres:
    build:
      context: docker/dev/postgres
      dockerfile: Dockerfile
    volumes:
      # Database volume
      - database:/var/lib/postgresql/data
      # Temp volume to allow using dumps
      - ./docker/dev/postgres/dumps/:/tmp/
    ports:
      - 54321:5432
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app

  # PostgreSQL testing database container
  postgres-testing:
    build:
      context: docker/dev/postgres
      dockerfile: Dockerfile
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app

  # 'Client' container
  client:
    build: docker/dev/client/.
    ports:
      - "3000:8080"
    working_dir: /home/node/app
    volumes:
      - ./client:/home/node/app
      - ./client/node_modules:/home/node/app/node_modules
    command: bash -c "npm install && npm run serve"
    environment:
      API_URL: 'http://localhost:8081/'

######### Volumes ###################################

volumes:
  database:
    driver: local
